name: tubular-topo
channels: [pytorch, nvidia, conda-forge]
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - scikit-image
  - scipy
  - networkx
  - numpy
  - matplotlib
  - pip
  - pip:
      - torch-geometric
      - nnunetv2
      - monai
      - wandb
      - nibabel
      - SimpleITK
